[build-system]
requires = ["setuptools>=68", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "audeo-2"
version = "0.4.0"
description = "Audeo-2"
requires-python = ">=3.10"
dependencies = [
  "toga>=0.4.5",
  "yt-dlp>=2026.01.29",
  "pillow>=10.0.0",
  "imageio-ffmpeg>=0.5.0",
]

[project.scripts]
audeo-2 = "audeo2.app:main"

[tool.setuptools]
package-dir = {"" = "src"}

[tool.setuptools.packages.find]
where = ["src"]
